# Generated by Django 2.2.4 on 2020-02-16 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kategori', '0002_auto_20200216_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='deskripsi',
            field=models.TextField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='harga',
            field=models.CharField(default=20, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
