# Generated by Django 2.2.10 on 2020-03-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martabakhome',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
