# Generated by Django 2.2.10 on 2020-03-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200309_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martabakhome',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
