# Generated by Django 2.2.4 on 2020-02-19 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilimage',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilimage',
            name='image',
            field=models.FileField(upload_to='uploadFile/profile/%y/%m/%d'),
        ),
    ]
