# Generated by Django 2.2.4 on 2020-02-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0002_auto_20200219_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilimage',
            name='user',
        ),
    ]
