# Generated by Django 2.2.4 on 2020-02-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0004_profilimage_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilimage',
            old_name='user',
            new_name='username',
        ),
    ]
