# Generated by Django 2.2.4 on 2020-02-19 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0005_auto_20200219_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilimage',
            name='username',
        ),
    ]
