# Generated by Django 2.2.4 on 2020-02-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0007_profilimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilimage',
            name='username',
        ),
    ]
