# Generated by Django 2.2.4 on 2020-02-19 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0008_remove_profilimage_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilimage',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
