# Generated by Django 2.2.4 on 2020-02-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0009_profilimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilimage',
            name='username',
        ),
        migrations.AlterField(
            model_name='profilimage',
            name='image',
            field=models.FileField(upload_to='upload/profile/%y/%m/%d'),
        ),
    ]
